version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: notification
    environment:
      POSTGRES_DB: notification_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local