server:
  port: 8081
spring:
  application:
    name: notificationservice
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  data:
    redis:
      port: 6379
      host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5433/notification_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver