server:
  port: 8080
spring:
  application:
    name: taskflow
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password
      authentication-database: admin
      database: taskflow
    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: taskflow-logs-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  elasticsearch:
    rest:
      uris: http://localhost:9200

  jackson:
    serialization:
      write-dates-as-timestamps: false