version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: event-db
    environment:
      POSTGRES_DB: event_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - event-db-data:/var/lib/postgresql/data

volumes:
  event-db-data:
    driver: local